import { TextField } from "@mui/material";
import { TextField, Button} from '@mui/material';
import styles from 'styles/btn.module.css';
import { useState } from 'react';


export default function Home() {
  const [username , setUsername] = useState("");
  const [password , setPassword] = useState("");


  const handleSubmit  = ()=> {
    console.log(username);
    console.log(password);
  }
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}


      <div className={styles.button}>
        <div >
          <TextField required className={styles.btn} value={username} onChange={(e)=> setUsername(e.target.value)} id="outlined-basic" label="Username" variant="outlined" />
        </div>
        <div>
          <TextField className={styles.btn} value={password} onChange={(e)=> setPassword(e.target.value)} id="outlined-basic" label="Password" variant="outlined" />
        </div>
        <div >
          <Button className={styles.btn1} variant="contained" onClick={handleSubmit}>Login</Button>
        </div>
      </div>


    </>
  )
}

